# Header
menu:
  Home: /hexo_3/
  Categories: /hexo_3/categories
  Archives: /hexo_3/archives
  rss: /hexo_3/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts