# Header
menu:
  Home: elbarco
  Archives: /hexo_3/archives
  rss: /hexo_3/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-147431281-1
favicon: /favicon.png

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts